version: '3.9'

services:
  server:
    container_name: server      
    ports:
      - 9999:9999
    image: server:1.0.0

    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      - test-net
    
networks:
  test-net:
    name: test-net