version: '3.9'

services:
  client:
    container_name: client
    image: ghcr.io/dgkwon90/study-github-actions/client:latest

    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - test-net

networks:
  test-net:
    name: test-net
    external: true
