# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Server Service Docker image
run-name: Server Service GitHub Actions 🚀

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'server/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Container Build and Push to registry
        uses: ./.github/actions/container-registry
        with:
          registry: 'ghcr.io'
          service_name: 'server'
          service_port: '9999'
